VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
echo Performing required docker pulls
docker pull openshift/centos-haproxy-simple-balancer
docker pull openshift/nodejs-0-10-centos
docker pull openshift/centos-mongodb
docker pull pmorie/parks-map-app
docker tag openshift/nodejs-0-10-centos nodejs-centos
docker tag pmorie/parks-map-app parks-map-app
echo Docker pulls done
echo Fetch from github
git clone git://github.com/pmorie/geard
cd geard
git checkout demo-multi
echo Done
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "atomic"
  config.vm.provision "shell", inline: $script

  config.vm.synced_folder './', '/vagrant', type: 'rsync', disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus =4
    v.customize ["modifyvm", :id, "--cpus", "4"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 4096
    libvirt.driver = 'kvm' # needed for kvm performance benefits!
    libvirt.connect_via_ssh = false
    libvirt.username = 'root'
  end

  config.vm.define "vm1", primary: true do |config|
    config.vm.network "forwarded_port", guest: 43273, host: 43273
    config.vm.network "forwarded_port", guest: 6060, host: 2225
    config.vm.network "forwarded_port", guest: 14000, host: 14000
    config.vm.network "private_network", ip: "192.168.205.10"
  end

  config.vm.define "vm2", primary: true do |config|
    config.vm.network "forwarded_port", guest: 43273, host: 53273
    config.vm.network "forwarded_port", guest: 6060, host: 12225
    config.vm.network "forwarded_port", guest: 14000, host: 24000
    config.vm.network "private_network", ip: "192.168.205.11"
  end

end
