#!/bin/bash -e

# release tag to push to
tag=${TAG:-latest}
release=${RELEASE:-268465}
# remote file name
name=${NAME:-gear}
# local file to upload
file=${FILE:-$name}
# github oauth token
token=${TOKEN}

curl -X POST "https://uploads.github.com/repos/openshift/geard/releases/$release/assets?name=$name" \
     -u $token:x-oauth-basic \
     -H "Content-Type: application/octet-stream" \
     -T $file \
     --silent
echo
