#!/bin/bash

# FIXME escape me
user=$1

trap "" 13

dir=$(find /var/lib/gears/access/gears/ssh/ -maxdepth 2 -name "${user}" -type d -print -quit)
matches=$(find $dir -maxdepth 1 -type l)
if [ "$matches" != "" ]; then
  while read -r line; do
      echo "command=\"/usr/bin/geard-ssh-shell\",environment=\"SSH_ORIGINAL_USER=$user\",environment=\"SSH_SOURCE_GEARS=ssh\",no-user-rc $(cat $line)"
  done <<< "$matches"
fi

dir=$(find /var/lib/gears/access/git/ -name "${user}" -type d -print -quit)
matches=$(find $dir -maxdepth 1 -name *.read -type l)
if [ "$matches" != "" ]; then
  while read -r line; do
      echo "command=\"/usr/bin/geard-git-shell\",environment=\"SSH_ORIGINAL_USER=$user\",environment=\"SSH_SOURCE_GEARS=git-read\",no-user-rc $(cat $line)"
  done <<< "$matches"
fi

matches=$(find $dir -maxdepth 1 -name *.write -type l)
if [ "$matches" != "" ]; then
  while read -r line; do
      echo "command=\"/usr/bin/geard-git-shell\",environment=\"SSH_ORIGINAL_USER=$user\",environment=\"SSH_SOURCE_GEARS=git-write\",no-user-rc $(cat $line)"
  done <<< "$matches"
fi