#!/bin/bash

# Constructs a usable environment for geard builds and tests.
#
# Exports the following:
#   GOPATH       - The original GOPATH with geard vendor source appended
#   PATH         - The original PATH with the usual system dirs appended
function setup_geard_build_env() {
  # Sanity check for GOPATH
  if [ "${GOPATH:-}" == "" ]; then
    echo "Must set GOPATH"
    exit 1
  fi

  # Inject the geard vendor dir into the GOPATH
  local DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  export GOPATH=$DIR/../vendor:$GOPATH
  echo "Building with GOPATH: ${GOPATH}"

  # Allow portable references to binaries like cp
  export PATH=$PATH:/bin:/usr/bin:/usr/local/bin
}
