#!/bin/bash -x
#GOOS=linux GOARCH=amd64 go build -o geard.linux64 geard/main.go
go get ./...
go build -o gear .
go install ./support/switchns

sudo /usr/bin/cp -f $GOPATH/bin/switchns .
sudo /usr/bin/cp -f gear /usr/bin/

