#!/bin/bash -x
#GOOS=linux GOARCH=amd64 go build -o geard.linux64 geard/main.go
go get -tags selinux ./...
go build -tags selinux -o gear .
go install -tags selinux ./support/switchns
go install -tags selinux ./support/gear-auth-keys-command

sudo /usr/bin/cp -f $GOPATH/bin/gear-auth-keys-command .
sudo /usr/bin/cp -f $GOPATH/bin/switchns .
sudo /usr/bin/cp -f gear /usr/bin/
