#!/bin/bash -x
#GOOS=linux GOARCH=amd64 go build -o geard.linux64 geard/main.go
go get -tags selinux ./...
go build -tags selinux -o gear .

go get -t -tags selinux "github.com/kraman/geard-switchns"
go get -t -tags selinux "github.com/kraman/geard-util"

sudo mkdir -p /opt/geard/bin
sudo /usr/bin/cp -f $GOPATH/bin/geard-switchns $GOPATH/bin/geard-util /opt/geard/bin
