#!/bin/bash

# Start i counter if needed
[ -z $f ] && echo woot

if [ ! -f /tmp/resty ]; then
    echo "Downloading resty from the internet, this is insecure and a terrible idea.  Fix later"
    echo

    wget -qO /tmp/resty http://github.com/micha/resty/raw/master/resty
fi

i=${CLI_REQID:-1}
CLI_PORT=${CLI_PORT:-"8080"}

. /tmp/resty
resty http://localhost:${CLI_PORT}/token/__test__/ > /dev/null 2&>1

function list-examples
{
    echo "list-containers"
    echo "build-image git://github.com/pmorie/simple-html pmorie/fedora-mock test-app"
    echo "container test-app 0001"
    echo "started 0001"
    echo "stopped 0001"
    echo "log 0001"
    echo "repository not-implemented"
    echo "environment not-implemented"
}

# This can take a minute
function build-image
{
    # Example
    # build-image git://github.com/pmorie/simple-html pmorie/fedora-mock test-app
    CARTRIDGE_SOURCE=$1
    BASE_IMAGE_NAME=$2
    BUILD_TAG=$3

    PUT '/build-image' -q "u=${BUILD_TAG}&d=1&r=${CARTRIDGE_SOURCE}&i=$i&t=${BASE_IMAGE_NAME}"
    i=$(($i+1))
}

function list-containers {
    GET '/containers' -q "u=0&d=0&r=0&t=0&i=$i"
    i=$(($i+1))
}

function container
{
    # Example
    # container test-app 0001
    IMAGE_NAME=$1
    GEAR_ID=$2

    PUT /container -q "u=0&d=1&t=${IMAGE_NAME}&r=${GEAR_ID}&i=$i" -d '{"ports":[{"external":4343,"internal":8080}]}'
    i=$(($i+1))
}

# Not yet working

function started
{
    # Example
    # started 0001

    GEAR_ID=$1
    PUT /container/started -q "u=0&d=1&r=${GEAR_ID}&i=$i"
    i=$(($i+1))
}

function stopped
{
    # Example
    # stopped 0001

    GEAR_ID=$1
    PUT /container/stopped -q "u=0&d=1&r=${GEAR_ID}&i=$i"
    i=$(($i+1))
}

function log
{
    # Example
    # log 0001

    GEAR_ID=$1
    GET /container/log -q "u=0&d=1&r=${GEAR_ID}&i=$i"
    i=$(($i+1))
}

function repository
{
#    PUT /repository -q 'u=0&d=1&r=dddd&i=12'
    echo "not implemented"
}

function environment
{
    #PUT /environment -q 'u=0&d=1&r=1000&i=17' -d '{"env":[{"name":"foo","value":"bar"}]}'
    echo "not implemented"
}

cmd=$1

if [ -z $cmd ]; then
    echo "run list-examples to see a list of command examples"
    exit
fi

case "$1" in
    list-examples)  list-examples;;
    list-containers) list-containers;;
    build-image) build-image $2 $3 $4;;
    container) container $2 $3;;
    started) started $2;;
    stopped) stopped $2;;
    log) log $2;;
esac
