#!/bin/bash

#don't vendor docker or its dependencies
go get -t -d -v github.com/dotcloud/docker

ORIG_GOPATH=$GOPATH
mkdir -p $ORIG_GOPATH/src/github.com/openshift/geard/vendor
export GOPATH=$ORIG_GOPATH/src/github.com/openshift/geard/vendor:$ORIG_GOPATH

#vendor missing packages. (Repeat to get transitive dependencies)
for i in {1..10} ; do
  go get -d -v -t ./... 2>&1 | grep "(download)"
  if [ $? -ne 0 ]; then
    break
  fi
done
go get ./...

pushd $ORIG_GOPATH/src/github.com/openshift/geard/vendor
for i in `find $ORIG_GOPATH/src/github.com/openshift/geard/vendor -type d -name .git`; do
  pushd $i 2>&1 > /dev/null
  rev=`git log -1 | grep commit`
  echo "Based off upstream $rev" > ../VENDORED_REVISION
  echo "Vendored on `date`">> ../VENDORED_REVISION
  popd 2>&1 > /dev/null
  rm -rf $i
done

for i in `find $ORIG_GOPATH/src/github.com/openshift/geard/vendor -type d -name .hg`; do
  pushd $i 2>&1 > /dev/null
  rev=`hg log -l 1 | grep changeset`
  echo "Based off upstream $rev" > ../VENDORED_REVISION
  echo "Vendored on `date`" >> ../VENDORED_REVISION
  popd 2>&1 > /dev/null
  rm -rf $i
done

git add $ORIG_GOPATH/src/github.com/openshift/geard/vendor/src
