#!/bin/bash
set -e

url=$1
commit=$2

GIT_DIR=${GIT_DIR:-/home/git/repo}
hooks_dir=${DEFAULT_HOOKS:-/home/git/default-hooks}

if [ -d "$GIT_DIR/objects" ]; then
  echo "SKIP: Repository exists"
  exit 0
fi

git --version

pushd $GIT_DIR > /dev/null 2>&1
if [ "$url" != "" ] && [ "$url" != "empty" ]; then
  echo "Using $url"
  git clone --bare --no-hardlinks "$url" .
  git config core.logAllRefUpdates true
  if [ "$commit" != "" ]; then
    echo "Using commit $commit"
    git reset --soft "$commit"
  fi
  git show-ref --verify --quiet refs/heads/master
  if [ $? -ne 0 ]; then
    git branch master
  fi
  git config pack.windowMemory 64m
  git repack
else
  git init --bare
  git config core.logAllRefUpdates true
  git config pack.windowMemory 64m
fi

mkdir -p ./.git/hooks
cp $hooks_dir/* ./.git/hooks
chmod ug+x ./.git/hooks/*